apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech1-green
  namespace: main
  labels:
    app: fintech1-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintech1-green
  template:
    metadata:
      labels:
        app: fintech1-green
    spec:
      containers:
      - name: fintech1-container
        image: 768331025805.dkr.ecr.us-east-1.amazonaws.com/fintech1:<IMAGE_TAG>
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
