name: Build and Deploy to EKS

on:
  push:
    branches:
      - main
      - staging      
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1.2.0

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./docker
          docker push $ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy Blue Deployment
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          NAMESPACE: ${{ github.ref_name }}          

        run: |                                          
          # Check if Blue exists, deploy if missing
          kubectl -n $NAMESPACE get deployment fintech1-blue || kubectl apply -f <(sed -e "s/<IMAGE_TAG>/$IMAGE_TAG/g" -e "s/<NAMESPACE>/$NAMESPACE/g" kubernetes/blue-deployment.yaml)
          kubectl -n $NAMESPACE rollout status deployment/fintech1-blue

          kubectl -n $NAMESPACE get deployment fintech1-blue -o jsonpath='{.status.readyReplicas}'
          kubectl -n $NAMESPACE patch service fintech1 -p '{"spec":{"selector":{"app":"fintech1-blue"}}}'
          sleep 10

      - name: Deploy Green Deployment
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          NAMESPACE: ${{ github.ref_name }}                    
        run: |
          # Deploy Green
          kubectl apply -f <(sed -e "s/<IMAGE_TAG>/$IMAGE_TAG/g" -e "s/<NAMESPACE>/$NAMESPACE/g" kubernetes/green-deployment.yaml)          
          kubectl -n $NAMESPACE rollout status deployment/fintech1-green

      - name: Switch Traffic to Green
        env:
          NAMESPACE: ${{ github.ref_name }}                          
        run: |
          kubectl -n $NAMESPACE get deployment fintech1-green -o jsonpath='{.status.readyReplicas}'        
          kubectl -n $NAMESPACE patch service fintech1 -p '{"spec":{"selector":{"app":"fintech1-green"}}}'
          sleep 10

      - name: Clean Up Blue Deployment
        env:
          NAMESPACE: ${{ github.ref_name }}      
        run: |
          kubectl -n $NAMESPACE delete deployment fintech1-blue || true

      - name: Verify Deployment
        env:
          NAMESPACE: ${{ github.ref_name }}      
        run: |
          kubectl -n $NAMESPACE get pods -o wide
          kubectl -n $NAMESPACE get services -o wide



